//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attandence
    {
        public int Id { get; set; }
        public Nullable<int> EmployeId { get; set; }
        public Nullable<System.DateTime> DateOfAttandence { get; set; }
        public Nullable<System.TimeSpan> CheckInTime { get; set; }
        public Nullable<System.TimeSpan> CheckOutTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> CheckOutStatus { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
